## Naukri Website Datascraping for DataScience Jobs

Datascraping is an essential tool to get data through vast resource of internet. It is mainly done through two methods: 
1)Using APIs
2)Scraping website
Here, we are scraping naukri website to get information on available data science jobs in India. This techniques uses extensive information of HTML tags and selenium library.

In [1]:
#Importing Library
import pandas as pd
import bs4
import selenium
import requests

In [2]:
#Importing webdriver, used to automatically run chrome
from selenium import webdriver

Naukri Website

In [3]:
browser = webdriver.Chrome('chromedriver.exe')
naukri= "https://www.naukri.com/data-science-jobs"
browser.get(naukri)

In [7]:
jobs = browser.find_elements_by_css_selector('div.row[type="tuple"]')
print(len(jobs))

50

In [5]:
for job in jobs:
    job_title = job.find_element_by_css_selector('li.desig')
    job_title = job_title.get_attribute('title')
    print(job_title)
    
    company = job.find_element_by_css_selector('span.org')
    company = company.get_attribute('innerHTML')
    print(company)

Data Science Course Mentor - Datatrained
DataTrained
Data Analyst / Data Science- Excel,sql,power BI, R, SAS- Fresher/exp
SLA Consultants India
Opening for Data Science Professional @ Applied Materials - Bangalore
Applied Materials India Private Limited
Director - Data Science - Product Setup
CareerNet Consulting
Big Data Architect - Data Science/hadoop
Triquetro Infotech Pvt Ltd
Big Data Architect - Data Science/hadoop
Triquetro Infotech Pvt Ltd
Data Science - Freshers
WNS GLOBAL SERVICES PRIVATE LIMITED
Walk-in for Data Scientist/ Data Analyst @ ADF DATA Science- Chennai
ADF <font class="hlite">Data</font> <font class="hlite">Science</font> Private Limited
Director - Data Science
Rinalytics Advisors
Vice President - Data Scientist - Data Science Practice
Crescendo Global
Manager - Data Science/machine Learning
Crescendo Global
Engineering Manager (Web Technologies/ Data Science)
Collins Aerospace (Rockwell Collins)
Strategic Project & Operations - Data Science Associate
BlackRock Services India Pvt. Ltd.
Walk-in for Python/django Developer @ ADF DATA Science PVT Ltd-chennai
ADF <font class="hlite">Data</font> <font class="hlite">Science</font> Private Limited
Data Science
JOBSLOTS TECHNOLOGIES PRIVATE LIMITED
Opportunity - Data Science (manager Level)
Kelly Outsourcing and Consulting Group India  Private Limited
Data Science Engineer_ 7+ Yrs _visakhapatnam
I Square Soft
Data Science Intern
Cogdina Inc
Opening For FULL / PART TIME Trainer in DATA Science/ Machine Learning
<font class="hlite">Data</font> <font class="hlite">Science</font> / Machine LearningTrainer
Data Science Engineer- MNC in Bglr
Artemis technologies
Urgent Requirement in Data Science
Mitosis Technologies Pvt. Ltd.,
Looking for Freelancer Trainer into Data Science- R Language
iPrimed Education Solutions Pvt Ltd
Data Scientist - Ahmedabad (immediate / Early Joinee)
Azilen Technologies Pvt Ltd
Data Science & Machine Learning Role - Python/sql/r/etl/scala
Ã‚&nbsp;3D India Staffing Research &amp; Consulting Pvt Ltd
Opening for Data Science Architect (AI Architect) 9 Yrs to 14 yrs
Techs to Suit Inc
Specialist - Data Science
Brainsearch Consulting Pvt Ltd.
Marketing Data Science Professional - SAS
Huquo Consulting Pvt. Ltd
Chief Intelligence Officer - Data Science & Analytics
TalPro
Chief Intelligence Officer - Data Science & Analytics
TalPro
Manager - Data Science - IT
Confidential
Data Science Professional
Geek Technologies
Data Science Lead
Finisar Technology India Pvt Ltd
Machine Learning / Data Science Conultants  - H1B Transfer Only
<font class="hlite">Data</font> Core Systems Inc.
Specialist - Data Science
Brainsearch Consulting Pvt Ltd.
Data Science/analysis Expert - Machine Learning
Catalyst
Python Developer - Data Science Applications
Startup - VideoKen
Data Science Analyst
IRIS SOFTWARE Inc
Data Science & Machine Learning
3D India Group
Manager - Data Science & Analytics with TOP US MNC
BIZ2CREDIT INFO SERVICES PVT LTD
Group Manager - Data Science - Python/nlp
Staffio HR
Computer Scientist - Data Science
PacsysHire
Manager- Data Science (customer Insights)
Wolters Kluwer India Pvt Ltd
Senior Analyst- Data Science (NLP Specialist)
Wolters Kluwer India Pvt Ltd
Analytics Specialist - Data Science & Big Data
TransOrg Analytics
Crisil- Data Science
CRISIL LIMITED
Data Science Project Lead Noida
Client Of Sampoorna
Jr. Data Scientist
Proseon Technologies pvt. ltd.
Data Scientist - Machine Learning/predictive Modeling
Maxonic Consulting
Junior Data Scientist
Invecas technologies Pvt Ltd
Data Engineer - ETL/ Java/ Python
Spectrum Consulting

In [6]:
def get_info(job, selector, attribute):
    try:
        tag = job.find_element_by_css_selector(selector)
        tag = tag.get_attribute(attribute)
    except:
        tag = None
    return tag

df_jobs = pd.DataFrame(columns = ['title', 'company', 'salary', 'date', 
                                 'location', 'experience', 'description', 'url'])

for job in jobs:
    job_title = get_info(job, 'li.desig', 'title')
    company = get_info(job, 'span.org', 'innerHTML')
    salary = get_info(job, 'span.salary', 'innerHTML')
    date = get_info(job, 'span.date', 'innerHTML')
    
    parent_location = job.find_element_by_css_selector('span.loc')
    location = get_info(parent_location, 'span', 'innerHTML')
    experience = get_info(job, 'span.exp', 'innerHTML')
    description = get_info(job, 'span.desc', 'innerHTML')
    url = get_info(job, 'a.content','href' )
    
    curr_job = {'title': job_title,
               'company': company,
               'salary':salary,
               'date':date,
               'location':location,
               'experience':experience,
               'description':description,
               'url': url}
    df_jobs = df_jobs.append(curr_job, ignore_index = True)

df_jobs

,title,company,salary,date,location,experience,description,url
0,Data Science Course Mentor - Datatrained,DataTrained,<em></em> Not disclosed,Today,"Delhi NCR, Mumbai, Bengaluru",<em></em>2-7 yrs,"DataTrained is an online <font class=""hlite"">D...",None
1,"Data Analyst / Data Science- Excel,sql,power B...",SLA Consultants India,"<em></em> 2,00,000 - 4,25,000 P.A.",Today,"Delhi NCR, Gurgaon, Noida",<em></em>0-5 yrs,None,None
2,Opening for Data Science Professional @ Applie...,Applied Materials India Private Limited,<em></em> Not disclosed,1 day ago,Bengaluru(Whitefield),<em></em>0-4 yrs,Experience at using statistical software appli...,None
3,Director - Data Science - Product Setup,CareerNet Consulting,<em></em> Not disclosed,2 days ago,Delhi,<em></em>9-14 yrs,- The ideal candidate will have a good underst...,None
4,Big Data Architect - Data Science/hadoop,Triquetro Infotech Pvt Ltd,<em></em> Not disclosed,2 days ago,Bengaluru,<em></em>11-15 yrs,- Should have skill sets for building high per...,None
5,Big Data Architect - Data Science/hadoop,Triquetro Infotech Pvt Ltd,<em></em> Not disclosed,2 days ago,Bengaluru,<em></em>5-10 yrs,- Should have skill sets for building high per...,None
6,Data Science - Freshers,WNS GLOBAL SERVICES PRIVATE LIMITED,<em></em> Not disclosed,2 days ago,Gurgaon,<em></em>0-0 yrs,a)\tCandidate should exhibit appetite for <fon...,None
7,Walk-in for Data Scientist/ Data Analyst @ ADF...,"ADF <font class=""hlite"">Data</font> <font clas...","<em></em> 5,00,000 - 15,00,000 P.A.",6 days ago,Chennai,<em></em>0-3 yrs,Experience with NoSQL and distributed <font cl...,None
8,Director - Data Science,Rinalytics Advisors,<em></em> Not disclosed,2 days ago,India,<em></em>10-15 yrs,Masters or PhD with experience in the area of ...,None
9,Vice President - Data Scientist - Data Science...,Crescendo Global,<em></em> Not disclosed,3 days ago,Bengaluru,<em></em>10-18 yrs,"- 10+ years of experience into <font class=""hl...",None
10,Manager - Data Science/machine Learning,Crescendo Global,<em></em> Not disclosed,3 days ago,Gurgaon,<em></em>6-8 yrs,- 6 to 8 years of experience in analytics or <...,None
11,Engineering Manager (Web Technologies/ Data Sc...,Collins Aerospace (Rockwell Collins),<em></em> Not disclosed,2 days ago,Bengaluru,<em></em>8-13 yrs,Experience in writing the system/subsystem/sof...,None
12,Strategic Project & Operations - Data Science ...,BlackRock Services India Pvt. Ltd.,<em></em> Not disclosed,5 days ago,Gurgaon,<em></em>5-8 yrs,Candidates should have experience or interest ...,None
13,Walk-in for Python/django Developer @ ADF DATA...,"ADF <font class=""hlite"">Data</font> <font clas...","<em></em> 4,00,000 - 9,00,000 P.A.",6 days ago,Chennai,<em></em>1-5 yrs,Proven experience with cross-platform and cros...,None
14,Data Science,JOBSLOTS TECHNOLOGIES PRIVATE LIMITED,<em></em> Not disclosed,4 days ago,Noida,<em></em>5-10 yrs,Strong development experience in open source t...,None
15,Opportunity - Data Science (manager Level),Kelly Outsourcing and Consulting Group India ...,<em></em> Not disclosed,3 days ago,Bengaluru,<em></em>4-7 yrs,"Experience using <font class=""hlite"">data</fon...",None
16,Data Science Engineer_ 7+ Yrs _visakhapatnam,I Square Soft,<em></em> Not disclosed,4 days ago,Visakhapatnam,<em></em>7-10 yrs,Experience with Agile Development (preferably ...,None
17,Data Science Intern,Cogdina Inc,<em></em> Not disclosed,4 days ago,Ahmedabad,<em></em>0-1 yrs,None,None
18,Opening For FULL / PART TIME Trainer in DATA S...,"<font class=""hlite"">Data</font> <font class=""h...","<em></em> 1,25,000 - 3,00,000 P.A.",30 days ago,Noida,<em></em>0-2 yrs,None,None
19,Data Science Engineer- MNC in Bglr,Artemis technologies,"<em></em> 10,00,000 - 15,00,000 P.A.",5 days ago,Bengaluru,<em></em>4-8 yrs,"2 years experience in <font class=""hlite"">data...",None
20,Urgent Requirement in Data Science,"Mitosis Technologies Pvt. Ltd.,",<em></em> Not disclosed,9 days ago,Chennai,<em></em>3-8 yrs,None,None
21,Looking for Freelancer Trainer into Data Scien...,iPrimed Education Solutions Pvt Ltd,"<em></em> 4,00,000 - 8,00,000 P.A.",10 days ago,Bengaluru,<em></em>3-8 yrs,None,None
22,Data Scientist - Ahmedabad (immediate / Early ...,Azilen Technologies Pvt Ltd,<em></em> Not disclosed,Today,Ahmedabad,<em></em>3-5 yrs,Candidate is expected to have 2 years or more ...,None
23,Data Science & Machine Learning Role - Python/...,Ã‚&nbsp;3D India Staffing Research &amp; Consul...,<em></em> Not disclosed,13 days ago,"Gurgaon, Gurugram",<em></em>5-9 yrs,- Have good time management skills and should ...,None
24,Opening for Data Science Architect (AI Archite...,Techs to Suit Inc,<em></em> Not disclosed,16 days ago,Greater Noida,<em></em>9-14 yrs,2: Professional Experience: Exposure to at lea...,None
25,Specialist - Data Science,Brainsearch Consulting Pvt Ltd.,<em></em> Not disclosed,20 days ago,"Bengaluru, Gurgaon",<em></em>7-12 yrs,"- Experience with one or more <font class=""hli...",None
26,Marketing Data Science Professional - SAS,Huquo Consulting Pvt. Ltd,<em></em> Not disclosed,20 days ago,Gurgaon,<em></em>2-5 yrs,"- Expertise in Excel and SQL required, experie...",None
27,Chief Intelligence Officer - Data Science & An...,TalPro,<em></em> Not disclosed,20 days ago,"Delhi NCR, Mumbai, Bengaluru, Gurgaon",<em></em>8-12 yrs,"- 10+ years in <font class=""hlite"">Data</font>...",None
28,Chief Intelligence Officer - Data Science & An...,TalPro,<em></em> Not disclosed,20 days ago,"Delhi NCR, Mumbai, Bengaluru, Gurgaon",<em></em>8-12 yrs,"- 10+ years in <font class=""hlite"">Data</font>...",None
29,Manager - Data Science - IT,Confidential,<em></em> Not disclosed,23 days ago,Delhi NCR,<em></em>4-7 yrs,- Graduate with an engineering degree (prefera...,None
30,Data Science Professional,Geek Technologies,<em></em> Not disclosed,24 days ago,Bengaluru(Jayanagar),<em></em>9-12 yrs,Roles: Establish AI/ML development standa...,None
31,Data Science Lead,Finisar Technology India Pvt Ltd,<em></em> Not disclosed,21 days ago,Hyderabad,<em></em>5-7 yrs,He/She should have 3-5 years relevant work exp...,None
32,Machine Learning / Data Science Conultants - ...,"<font class=""hlite"">Data</font> Core Systems Inc.",<em></em> Not disclosed,30+ days ago,United States (U.S),<em></em>8-13 yrs,At least four years of progressively ambitious...,None
33,Specialist - Data Science,Brainsearch Consulting Pvt Ltd.,<em></em> Not disclosed,30+ days ago,"Delhi NCR, Bengaluru, Gurgaon",<em></em>7-12 yrs,"- Experience with one or more <font class=""hli...",None
34,Data Science/analysis Expert - Machine Learning,Catalyst,<em></em> Not disclosed,30+ days ago,Bengaluru,<em></em>2-6 yrs,- Hands on experience in managing DWH and ETL ...,None
35,Python Developer - Data Science Applications,Startup - VideoKen,<em></em> Not disclosed,30+ days ago,Bengaluru,<em></em>4-6 yrs,- 4+ years development experience in python;- ...,None
36,Data Science Analyst,IRIS SOFTWARE Inc,<em></em> Not disclosed,30+ days ago,Delhi NCR,<em></em>4-8 yrs,Understanding of IBM Watson is added advantage...,None
37,Data Science & Machine Learning,3D India Group,<em></em> Not disclosed,30+ days ago,Gurgaon,<em></em>5-9 yrs,- Have good time management skills and should ...,None
38,Manager - Data Science & Analytics with TOP US...,BIZ2CREDIT INFO SERVICES PVT LTD,"<em></em> 15,00,000 - 20,00,000 P.A. Other ...",30+ days ago,Noida,<em></em>4-8 yrs,Incumbent must have Operational understanding ...,None
39,Group Manager - Data Science - Python/nlp,Staffio HR,<em></em> Not disclosed,30+ days ago,Bengaluru,<em></em>6-11 yrs,This is a Team management role - Skill set -...,None
40,Computer Scientist - Data Science,PacsysHire,<em></em> Not disclosed,30+ days ago,Bengaluru,<em></em>1-5 yrs,We are looking for talented engineers who are ...,None
41,Manager- Data Science (customer Insights),Wolters Kluwer India Pvt Ltd,<em></em> Not disclosed,30+ days ago,Pune(Kalyani Nagar),<em></em>8-13 yrs,Qualifications: \t Education- Bachel...,None
42,Senior Analyst- Data Science (NLP Specialist),Wolters Kluwer India Pvt Ltd,<em></em> Not disclosed,30+ days ago,Pune(Kalyani Nagar),<em></em>5-9 yrs,We are seeking a Language Engineer with experi...,None
43,Analytics Specialist - Data Science & Big Data,TransOrg Analytics,<em></em> Not disclosed,30+ days ago,Mumbai,<em></em>2-5 yrs,"- Knowledge of big <font class=""hlite"">data</f...",None
44,Crisil- Data Science,CRISIL LIMITED,<em></em> Not disclosed,30+ days ago,Pune,<em></em>2-4 yrs,"Experience in <font class=""hlite"">data</font> ...",None
45,Data Science Project Lead Noida,Client Of Sampoorna,<em></em> Not disclosed,4 days ago,Noida,<em></em>8-11 yrs,Candidate Experience Should Be : 8 To 11 Candi...,None
46,Jr. Data Scientist,Proseon Technologies pvt. ltd.,<em></em> Not disclosed,Today,Vadodara,<em></em>0-1 yrs,None,None
47,Data Scientist - Machine Learning/predictive M...,Maxonic Consulting,<em></em> Not disclosed,1 day ago,Noida,<em></em>2-5 yrs,- Should have an expert command of statistical...,None
48,Junior Data Scientist,Invecas technologies Pvt Ltd,<em></em> Not disclosed,1 day ago,Hyderabad,<em></em>3-5 yrs,Experience with deep learning and cognitive se...,None
49,Data Engineer - ETL/ Java/ Python,Spectrum Consulting,<em></em> Not disclosed,1 day ago,Chennai,<em></em>5-10 yrs,- You have experience with building stream-pro...,None